# Generated by Django 4.2 on 2023-05-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.article'),
        ),
    ]
