# Generated by Django 4.2 on 2023-05-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_reply_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(),
        ),
    ]
